version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${DATA_DIR}/data:/app/data
      - ${DATA_DIR}/logs:/app/logs
      - ${DATA_DIR}/models:/app/models
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - redis
    deploy:
      resources:
        limits:
          memory: 1G

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          memory: 256M

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - '80:80'
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  mongodata:
  redisdata: