version: '3.8'

services:
  # Frontend avec hot reload
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: voxkill-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - voxkill-dev

  # Backend avec nodemon
  backend:
    build:
      context: .
      target: dev
    container_name: voxkill-backend-dev
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:devpassword@mongodb:27017/voxkill-dev?authSource=admin
      - REDIS_URL=redis://:devpassword@redis:6379
    networks:
      - voxkill-dev
    depends_on:
      - mongodb
      - redis

  # MongoDB pour dev
  mongodb:
    image: mongo:7-jammy
    container_name: voxkill-mongodb-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: devpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - voxkill-dev

  # Redis pour dev
  redis:
    image: redis:7-alpine
    container_name: voxkill-redis-dev
    command: redis-server --requirepass devpassword
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - voxkill-dev

volumes:
  mongodb_dev_data:
  redis_dev_data:

networks:
  voxkill-dev:
    driver: bridge